-- VERSÃO 2 ONLINE
-- Supabase/PostgreSQL.
-- O Excel continua sendo usado para importar/exportar dados, mas as gravações
-- simultâneas ficam no banco online para evitar conflitos entre usuários.

create table if not exists public.base_dados (
  id bigint generated by default as identity primary key,
  local text,
  uf text,
  filial text,
  cultura text,
  lote text not null unique,
  cultivar text,
  cat text,
  pen text,
  um text,
  tratamento text,
  qtd_sistema numeric,
  peso_etiqueta numeric,
  created_at timestamptz default now()
);

create table if not exists public.auditorias (
  id bigint generated by default as identity primary key,
  local text not null,
  uf text,
  filial text,
  cultura text,
  lote text not null,
  cultivar text,
  cat text,
  pen text,
  um text,
  tratamento text,
  qtd_sistema numeric,
  peso_etiqueta numeric,
  data_verificacao date,
  mes text,
  auditor_pcp text,
  auditor_unidade text,
  responsavel_ubs text,
  cat_fis text,
  etiqueta_fisica text,
  qtd_fisica numeric,
  camara text,
  quadra text,
  fileira text,
  observacao text,
  status text,
  divergencia text,
  origem text default 'BASE',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(local,lote)
);

alter table public.base_dados enable row level security;
alter table public.auditorias enable row level security;

-- Para o primeiro teste interno, leitura/gravação pública via publishable key.
-- Antes de colocar o link fora da empresa, recomendamos ativar Auth e trocar
-- estas policies por policies baseadas em usuários.
create policy "base_dados_select" on public.base_dados for select to anon, authenticated using (true);
create policy "base_dados_insert" on public.base_dados for insert to anon, authenticated with check (true);
create policy "base_dados_update" on public.base_dados for update to anon, authenticated using (true) with check (true);

create policy "auditorias_select" on public.auditorias for select to anon, authenticated using (true);
create policy "auditorias_insert" on public.auditorias for insert to anon, authenticated with check (true);
create policy "auditorias_update" on public.auditorias for update to anon, authenticated using (true) with check (true);

create index if not exists idx_base_local on public.base_dados(local);
create index if not exists idx_aud_local on public.auditorias(local);
create index if not exists idx_aud_lote on public.auditorias(lote);
