
-- V2 FINAL - estrutura baseada na planilha real "Resultados".
-- IMPORTANTE: execute este script apenas se as tabelas atuais ainda estiverem sem dados.
-- Ele recria a estrutura correta para histórico de múltiplas auditorias do mesmo lote.

drop table if exists public.auditorias cascade;
drop table if exists public.base_dados cascade;

create table public.base_dados (
  id bigint generated by default as identity primary key,
  local text,
  uf text,
  filial text,
  deposito text,
  cultura text,
  lote text not null unique,
  cultivar text,
  cod_produto text,
  nome_produto_erp text,
  cat text,
  pen text,
  um text,
  qtd_sistema numeric,
  peso_etiqueta numeric,
  created_at timestamptz default now()
);

create table public.auditorias (
  id bigint generated by default as identity primary key,
  local text,
  uf text,
  filial text,
  deposito text,
  cultura text,
  lote text not null,
  cultivar text,
  cod_produto text,
  nome_produto_erp text,
  cat text,
  pen text,
  um text,
  qtd_sistema numeric,
  peso_etiqueta numeric,
  cat_fis text,
  etiqueta_fisica text,
  qtd_fisica numeric,
  camara text,
  quadra text,
  fileira text,
  conf_sim_nao text,
  n_lotes numeric,
  data_verificacao date,
  mes text,
  auditor_pcp text,
  auditor_unidade text,
  responsavel_ubs text,
  status text,
  divergencia text,
  observacao text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.base_dados enable row level security;
alter table public.auditorias enable row level security;

create policy "base_dados_select" on public.base_dados for select to anon, authenticated using (true);
create policy "base_dados_insert" on public.base_dados for insert to anon, authenticated with check (true);
create policy "base_dados_update" on public.base_dados for update to anon, authenticated using (true) with check (true);

create policy "auditorias_select" on public.auditorias for select to anon, authenticated using (true);
create policy "auditorias_insert" on public.auditorias for insert to anon, authenticated with check (true);
create policy "auditorias_update" on public.auditorias for update to anon, authenticated using (true) with check (true);

create index idx_base_local on public.base_dados(local);
create index idx_base_lote on public.base_dados(lote);
create index idx_aud_local_data on public.auditorias(local,data_verificacao);
create index idx_aud_lote on public.auditorias(lote);
